name: Elsa Ducrot
author: Elsa Ducrot
description: PhD student
github: http://www.github.com/educrot
twitter: https://twitter.com/ElsaDucrot
linkedin: https://www.linkedin.com/in/elsa-ducrot-440300140/
email: educrot@uliege.be
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
