name: Herring Cove
author: Elsa Ducrot
description: theme for jekyll
github: http://www.github.com/educrot
twitter: http://www.twitter.com/
linkedin: http://www.linkedin.com
email: rnpatel[at]me.com
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
